### ISSUE TITLE
naoyarisma.com SMS problem

### ISSUE THREAD

**Issue by CALPARDO** [ArdaGurcan/naoyarisma.com#1]
When I enter naoyarisma.com, I don't get any SMS from Nesibe Mommy. What is the problem, what am I doing wrong?

Thank you!

OS: Windows 10
Browser: Opera

**Comment by ArdaGurcan** [comment]
You shouldn't have used Windows 10; try using Windows XP instead.

**Comment by CALPARDO** [comment]
Same problem. Nothing changed.

**Comment by albatros8146** [comment]
> When I enter naoyarisma.com, I don't get any SMS from Nesibe Mommy. What is the problem, what am I doing wrong?
> 
> Thank you!
> 
> OS: Windows 10
> Browser: Opera

I have the same problem too! I think Nesibe Mommy is sleeping these days
